### ISSUE TITLE
Build failed when use tns plugins

### ISSUE THREAD

**Issue by academici** [rigor789/nativescript-vue-webpack-template#4]
I use node 9.3, npm 5.6, android studio 3.2, nativescript 3.4.1
Install nativescript-pro-ui and nativescript-gradient

Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient)
Vue.registerElement(
  'RadSideDrawer',
  () => require('nativescript-pro-ui/sidedrawer').RadSideDrawer
)

Build error with RadSideDrawer
`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vue.webpack/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Could not load view for: radsidedrawer. Error: com.tns.NativeScriptException: Failed to find module: "../../styling/background", relative to: app/`

Build error with gradient
`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vue.webpack/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Could not load view for: gradient. Error: com.tns.NativeScriptException: Failed to find module: "./stack-layout-common", relative to: app/`

when using other plugins I get similar errors

**Comment by sergioIGZ** [comment]
i can register this plugin (its working here) https://play.nativescript.org/?template=play-vue&id=pAMaae&v=4
what i've done is "npm run tns -- add plugin 'pluginname'" so its registered on the dist/package.json
the problem is i cannot use afterwards in the template, it throws this error:

> TypeError: Could not load view for: pulltorefresh. Error: com.tns.NativeScriptException: Failed to find module: "../core/view", relative to: app/


if i remove "<PullToRefresh>" tags it works (i mean the register doesn't throw any error)


```
console.log('entry.native.js')
const Vue = require('nativescript-vue')
import ProductList from './components/ProductList.vue'
import Categories from './components/Categories.vue'
import VueRouter from 'vue-router'
import store from './store/index-native'
Vue.registerElement("PullToRefresh", () => require("nativescript-pulltorefresh").PullToRefresh)

Vue.use(VueRouter)
const router = new VueRouter({
  routes: [
    { path: '/categories', component: Categories },
    { path: '/product-list/:position', component: ProductList, props: true },
    { path: '*', redirect: '/categories' }
  ]
})

new Vue({
  router,
  store,
  template: `
    <Page ref="page">
      <StackLayout>
        <PullToRefresh @refresh="refreshList">
          <router-view />
        </PullToRefresh>
      </StackLayout>
    </Page>
  `,
  created: function () {
    this.$router.replace('/categories')
  },
  methods: {
    changeRoute(to) {
      router.replace(to)
    },
    refreshList(args) {
      setTimeout(() => {
        args.object.refreshing = false;
        alert('List has been refreshed! Wooohooo!')
      }, 2000)
    }
  }
}).$start();
```
