### ISSUE TITLE
web pack build is failing npm run dev doesnt work

### ISSUE THREAD

**Issue by suprithwork** [rigor789/nativescript-vue-webpack-template#7]
TypeError: Cannot read property 'thisCompilation' of undefined

**Comment by shmdesign** [comment]
same here

**Comment by xeoshow** [comment]
same here:
~~~
TypeError: Cannot read property 'thisCompilation' of undefined

**Comment by rigor789** [comment]
Please refer to the official docs on starting a new project. This template is deprecated and will not be updated.
